uploader:
  enabled: true
  package: yandextank.plugins.DataUploader
  job_name: pandora-perf-grpc-300inst-sleep0ms
  job_dsc: ''
  ver: ''
  api_address: loadtesting.api.cloud.yandex.net:443
pandora:
  enabled: true
  package: yandextank.plugins.Pandora
  pandora_cmd: ./pandora-perf
  config_content:
    pools:
      - id: gRPC
        gun:
          type: grpc
          target: '127.0.0.1:8091'
          tls: false
        ammo:
          type: grpc/json
          file: ./payload.json
        result:
          type: phout
          destination: ./phout.log
        startup:
          type: once
          times: 300
        rps:
          - type: line
            from: 1
            to: 40000
            duration: 60s
        discard_overflow: false
    log:
      level: error
    monitoring:
      expvar:
        enabled: true
        port: 1234
telegraf:
  enabled: true
  package: yandextank.plugins.Telegraf
  config:
    hosts:
      localhost: null
    metrics:
      cpu: null
      mem: null
      diskio: null
      net: null
      netstat: null
      system: null
      kernel: null
core: {}
