name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: Test
        run: go test -race -covermode atomic ./...

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o pandora_0.5.17_linux_amd64

      - name: Build Darwin
        run: GOOS=darwin GOARCH=amd64 go build -o pandora_0.5.17_darwin_amd64

      - name: Upload Release Asset Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pandora_0.5.17_linux_amd64
          asset_name: pandora_0.5.17_linux_amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pandora_0.5.17_linux_amd64
          asset_name: pandora_0.5.17_linux_amd64
          asset_content_type: application/octet-stream