name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        arch: [amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: Test
        run: go test -race -covermode atomic ./...

      - name: Set GITHUB_ENV
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "GOOS=linux" >> $GITHUB_ENV
          else
            echo "GOOS=darwin" >> $GITHUB_ENV
          fi
          echo $GOOS

      - name: Build
        run: |
          export GOARCH=${{ matrix.arch }}
          export CGO_ENABLED=0
          echo $GOOS
          go build -o pandora_${{ github.event.release.tag_name }}-${GOOS}-${{ matrix.arch }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pandora_${{ github.event.release.tag_name }}-${{ env.GOOS }}-${{ matrix.arch }}
          asset_name: pandora_${{ github.event.release.tag_name }}-${{ env.GOOS }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
