name: yc-load-testing-ci
run-name: yc-load-testing-ci
on: [ push ]
env:
  YC_LT_FOLDER_ID: b1g5mqk0rkb81u1kf2d4
  YC_LT_AUTHORIZED_KEY_JSON: ${{ secrets.YC_LOADTESTING_CI_AUTHORIZED_KEY_JSON }}
  YC_LT_TEST_AGENT_FILTER: "name = 'agent-pandora-perf-medium'"
  YC_LT_TEST_EXTRA_DESCRIPTION: "GitHub Actions workflow - ${{github.run_id}}"
  YC_LT_SKIP_TEST_CHECK: "1"
  YC_LT_OUTPUT_DIR: ${{github.workspace}}/performance-test/output

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true

      - name: Test
        run: go test -race -covermode atomic ./...

      - name: Build
        run: |
          export GOARCH=linux
          export CGO_ENABLED=0
          go build -o pandora_perf_2
