name: upload-pandora-cmd-s3
run-name: upload-pandora-cmd-s3
on: [ push ]
env:
  YC_LT_FOLDER_ID: b1gacohsvc2kc4d76tu5
  YC_LT_AUTHORIZED_KEY_JSON: ${{ secrets.YC_LOADTESTING_CI_AUTHORIZED_KEY_JSON }}
  YC_LT_TEST_AGENT_FILTER: "name = 'agent-pandora-perf-medium'"
  YC_LT_TEST_EXTRA_DESCRIPTION: "GitHub Actions workflow - ${{github.run_id}}"
  YC_LT_SKIP_TEST_CHECK: "1"
  YC_LT_OUTPUT_DIR: ${{github.workspace}}/performance-test/output

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yc

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true

      - name: Test
        run: go test -race -covermode atomic ./...

      - name: Build
        run: |
          export GOOS=linux
          export CGO_ENABLED=0
          go build -o pandora_perf_2

      - name: Upload
        run: |
          source performance-test/automation/_functions.sh && source performance-test/automation/_variables.sh; yc_s3_upload ./pandora_perf_2 pandora-perf pandora-perf
#          source performance-test/automation/s3_upload.sh ./pandora_perf_2 pandora-perf pandora-perf
