name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-unit-tests:
    name: Unit Tests
    concurrency:
      group: unit-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu, macOS]
    env:
      OS: ${{ matrix.os }}-latest
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Test
        run: go test -race -coverprofile unit.txt -covermode atomic ./...

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: unit,${{ matrix.os }},go-${{ matrix.go-version }}
          name: unit

      - name: Build
        run: go build -o pandora-${{ matrix.os }}-${{ matrix.go-version }}
