name: Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  run-unit-tests:
    name: Unit Tests
    concurrency:
      group: unit-${{ github.ref }}-${{ matrix.os }}-${{ matrix.go-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS]
    env:
      OS: ${{ matrix.os }}-latest
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true

      - name: Test
        run: go test -race -coverprofile unit.txt -covermode atomic ./...

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./unit.txt
          flags: unit,${{ matrix.os }},go-${{ matrix.go-version }}
          name: unit

  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yc
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true
      - name: Test
        run: go test -race -covermode atomic ./...
      - name: Build
        run: |
          export GOOS=linux
          export CGO_ENABLED=0
          go build -o pandora_perf_2
      - name: Upload
        run: |
          source performance-test/automation/_functions.sh && source performance-test/automation/_variables.sh; yc_s3_upload ./pandora_perf_2 pandora-perf ${YC_LT_DATA_BUCKET}

  test-pandora-perf:
    needs: [ build-and-upload ]
    runs-on: ubuntu-latest
    concurrency: { group: loadtesting }
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yc
      - name: Run Test HTTP-300inst-sleep0ms
        run: |
          stripped_tag="${{ github.event.release.tag_name }}"
          STRIPPED_TAG=${stripped_tag:1}
          YC_LT_VERBOSE=2 YC_LT_TEST_EXTRA_LABELS="version=${STRIPPED_TAG}" ./performance-test/automation/test.sh ./performance-test/test-config/pandora-perf-http-uri-300inst-sleep0ms
      - name: Upload Artifacts GRPC 300inst-sleep0ms
        uses: actions/upload-artifact@v4
        with:
          name: pandora-perf-grpc-300inst-sleep0ms
          path: ${{ env.YC_LT_OUTPUT_DIR }}
