name: performance-tests
run-name: performance-tests
on: [ push ]
env:
  YC_LT_FOLDER_ID: b1gacohsvc2kc4d76tu5
  YC_LT_AUTHORIZED_KEY_JSON: ${{ secrets.YC_LOADTESTING_CI_AUTHORIZED_KEY_JSON }}
  YC_LT_TEST_AGENT_FILTER: "name = 'agent-pandora-perf-medium'"
  YC_LT_TEST_EXTRA_DESCRIPTION: "GitHub Actions workflow - ${{github.run_id}}"
  YC_LT_SKIP_TEST_CHECK: "1"
  YC_LT_OUTPUT_DIR: ${{github.workspace}}/performance-test/output

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yc
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
          cache: true
      - name: Build
        run: |
          export GOOS=linux
          export CGO_ENABLED=0
          go build -o pandora_perf_2
      - name: Upload
        run: |
          source performance-test/automation/_functions.sh && source performance-test/automation/_variables.sh; yc_s3_upload ./pandora_perf_2 pandora-perf pandora-perf

  test-300inst-sleep0ms:
    needs: [ build-and-upload ]
    runs-on: ubuntu-latest
    concurrency: { group: loadtesting }
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yc
      - name: Run Test
        run: |
          stripped_tag="v0.5.26.alpha4"
          STRIPPED_TAG=${stripped_tag:1}
          YC_LT_TEST_EXTRA_LABELS="version=${STRIPPED_TAG}" ./performance-test/automation/test.sh ./performance-test/test-config/300inst-sleep0ms
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 300inst-sleep0ms
          path: ${{ env.YC_LT_OUTPUT_DIR }}
      - name: Run Test 2
        run: |
          stripped_tag="v0.5.26.alpha4"
          STRIPPED_TAG=${stripped_tag:1}
          YC_LT_TEST_EXTRA_LABELS="version=${STRIPPED_TAG}" ./performance-test/automation/test.sh ./performance-test/test-config/2000inst-sleep0ms
      - name: Upload Artifacts 2
        uses: actions/upload-artifact@v4
        with:
          name: 2000inst-sleep0ms
          path: ${{ env.YC_LT_OUTPUT_DIR }}
      - name: Run Test 3
        run: |
          stripped_tag="v0.5.26.alpha4"
          STRIPPED_TAG=${stripped_tag:1}
          YC_LT_TEST_EXTRA_LABELS="version=${STRIPPED_TAG}" ./performance-test/automation/test.sh ./performance-test/test-config/2000inst-sleep50ms
      - name: Upload Artifacts 3
        uses: actions/upload-artifact@v4
        with:
          name: 2000inst-sleep50ms
          path: ${{ env.YC_LT_OUTPUT_DIR }}

#  test-2000inst-sleep0ms:
#    needs: [ build-and-upload ]
#    runs-on: ubuntu-latest
#    concurrency: { group: loadtesting }
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/setup-yc
#      - name: Run Test
#        run: ./performance-test/automation/test.sh ./performance-test/test-config/2000inst-sleep0ms
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: 2000inst-sleep0ms
#          path: ${{ env.YC_LT_OUTPUT_DIR }}
#
#  test-2000inst-sleep50ms:
#    needs: [ build-and-upload ]
#    runs-on: ubuntu-latest
#    concurrency: { group: loadtesting }
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/setup-yc
#      - name: Run Test
#        run: ./performance-test/automation/test.sh ./performance-test/test-config/2000inst-sleep50ms
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: 2000inst-sleep50ms
#          path: ${{ env.YC_LT_OUTPUT_DIR }}
